### ISSUE TITLE
[Suggestion] Configuration to disable seed drops

### ISSUE THREAD

**Issue by Lordician** [Tiviacz1337/PizzaCraft#1]
I would like to see a configuration that will prevent stuff like olives and the different seeds from dropping.
I am playing with a couple of other mods that add tomatoes and peppers (Rustic) and i replace the ingredients with stuff from other mods so that there is more uses for those items as well.
Replacing them works by means of using Crafttweaker, but disabling the seeds from dropping is a bit more difficult.

**Comment by Tiviacz1337** [comment]
I will consider this suggestion! :)

**Comment by Tiviacz1337** [comment]
The config file will be added in the next update! :) (Probably 1.1.0)
