### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by Yomamasnuggets** [Tiviacz1337/PizzaCraft#10]
I have included you mod in my latest pack and the server it is running on seems to crash every time someone tries to break a pizza oven.

**Comment by Tiviacz1337** [comment]
Thanks for reporting this issue.
Could you tell me what are you doing with oven that it crashes (before destroying) server I'm placing and destroying oven and game works fine.

**Comment by Tiviacz1337** [comment]
Issue fixed in dev version.

**Comment by Yomamasnuggets** [comment]
sorry i could not respond i was at work.  I was not doing anything with the oven.  I tried to break it with a diamond pick to move it (in survival) and the server would crash.  i can break it in creative with no issue.
