### ISSUE TITLE
The `forge:rawchicken` and `forge:rawpork` tags do not exist

### ISSUE THREAD

**Issue by FreeFull** [Tiviacz1337/PizzaCraft#100]
Currently, the chopping recipes for raw chicken wings and ham depend on the forge:rawchicken and forge:rawpork tags, but those tags do not actually exist or have any items. Therefore, currently the raw chicken wings and ham items aren't obtainable.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files/all?page=1&pageSize=20 fixed
