### ISSUE TITLE
Pizza recursion overloads NBT

### ISSUE THREAD

**Issue by fengshuo2004** [Tiviacz1337/PizzaCraft#103]
## Description

It turns out that this mod and [Some Assembly Required](https://github.com/ochotonida/some-assembly-required) both saves the full NBT data of ingredients inside the pizza/sandwich items. This means by **putting a pizza inside a sandwich inside a pizza inside a sandwich inside a pizza**... you obtain an item with gigantic amount of NBT data that would crash the client as soon as it's placed into a tile entity.

![image](https://github.com/Tiviacz1337/PizzaCraft/assets/25703836/631d26f8-6f35-4f82-9a74-85e4e36e9386)

A friend on my server found this out the hard way. At this point, the pizza is inside a pizza station. Anyone close enough to load that chunk is kicked instantly and couldn't rejoin. This is effectively a chunk ban. We had to reset the entity data of the pizza station using a NBT editor.

![PizzaBomb](https://github.com/Tiviacz1337/PizzaCraft/assets/25703836/45d27898-b127-422b-8bd5-3367ed67635b)

Here's a picture of the sandwich one step before wreaking havoc:

![2023-09-24_16 26 16](https://github.com/Tiviacz1337/PizzaCraft/assets/25703836/15aca3b4-399b-4cfe-ac3a-bf5973604af5)

## To reproduce

1. Create sandwich using the sandwich station (from mod Some Assembly Required)
2. Put sandwiches into pizza station's ingredient slots
3. Create and cook the pizza
4. Slice the pizza and put the slices inside another sandwich
5. Repeat 2-4 until 9 sandwiches
6. Place back into the pizza station, you are instantly kicked along other players in chunk loading range

## Potential Fix

IMO the best fix would be to store the ID of ingredients inside the pizza without copying all their NBT data.

I've had a look at your code, in this function:

https://github.com/Tiviacz1337/PizzaCraft/blob/6d5bda0bbe957dffb1756bc1753107b36bef3aa6/src/main/java/com/tiviacz/pizzacraft/common/PizzaCalculator.java#L38

It calls `NBTUtils.saveInventoryToStack()` which seems to do a deep copy of the ingredients' data. You might want to change this to only copy the item ID instead.

Thanks.

**Comment by Tiviacz1337** [comment]
blacklisted sandwitch from some assembly required in pizza

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files/all?page=1&pageSize=20

**Comment by fengshuo2004** [comment]
@Tiviacz1337 Hi. Please re-open this issue. It turns out _Some Assembly Required_ is not the cause here. You can still crash client side by putting pizza inside a pizza inside a pizza inside a pizza... The NBT data of pizza ingredients MUST be sanitized to properly fix this.
