### ISSUE TITLE
Game Crashed right after right clicking pizza

### ISSUE THREAD

**Issue by TsGymCat** [Tiviacz1337/PizzaCraft#105]
Exception caught during firing event: IBakedModel::getQuads should never be called, only IForgeBakedModel::getQuads

https://paste.modularity.gg/paste/?content=https://cdn.discordapp.com/attachments/768367574001778729/1199998225386586122/latest.log?ex=65c4946f&is=65b21f6f&hm=de416658defda2074cef326e164644a56067b135dde5d36e145df41661f1ce7c&&raw=false#3110

**Comment by TsGymCat** [comment]
Suspected Mods are Carry On, Pizza Craft

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files/all?page=1&pageSize=20 fixed
