### ISSUE TITLE
ERROR CRASH

### ISSUE THREAD

**Issue by silvestrifacu** [Tiviacz1337/PizzaCraft#106]
Aternos Server.Tlauncher. 
[crash-2024-02-02_16.18.33-client.txt](https://github.com/Tiviacz1337/PizzaCraft/files/14150035/crash-2024-02-02_16.18.33-client.txt)

Game fatally crashes right when trying to chop ingredients with the knife. Error log: internal exception java.io.ioexception.

Created a new Tlauncher account and kept playing as it should be. Any solutions to get back my last account?

**Comment by Tiviacz1337** [comment]
not pizzacraft related, seems like crash comes from mr crayfish guns mod
