### ISSUE TITLE
mod loading error 

### ISSUE THREAD

**Issue by Thunderrock424242** [Tiviacz1337/PizzaCraft#109]
i will post my 2 logs here 

[latest.log](https://github.com/Tiviacz1337/PizzaCraft/files/15050487/latest.log)

[launcher_log.txt](https://github.com/Tiviacz1337/PizzaCraft/files/15050489/launcher_log.txt)

**Comment by Tiviacz1337** [comment]
Seems like you want to play 1.20.4 version of the mod on 1.20.1, download mod version for 1.20.1

**Comment by Thunderrock424242** [comment]
> Seems like you want to play 1.20.4 version of the mod on 1.20.1, download mod version for 1.20.1

I updated from the latest version on the 1.20.1
