### ISSUE TITLE
Cannot craft Pizza Dough and Pizzas using the Cooking for Blockheads' Cooking Table

### ISSUE THREAD

**Issue by fandomaniac** [Tiviacz1337/PizzaCraft#11]
You can't craft Pizza Dough and any of the PizzaCraft Pizzas using the Cooking for Blockheads' Cooking Table.

PizzaCraft version: 1.12.2-1.4.2
Cooking for Blockheads version: 1.12.2-6.4.69
Forge Version: 1.12.2 - 14.23.5.2814

**Comment by Tiviacz1337** [comment]
You can't craft those items, because they are not edible
