### ISSUE TITLE
Pizza Dough isn't craftable.

### ISSUE THREAD

**Issue by Renari** [Tiviacz1337/PizzaCraft#21]
It seems the recipe shown for pizza dough on the curseforge page no longer works. You can make flour with the mortar and pestle which can then be made into dough however it seems dough isn't used for anything and pizza dough has no crafting recipe.

Pizza dough is required to make every pizza.

PizzaCraft Version: 2.0.17.17

**Comment by Tiviacz1337** [comment]
You have to place pizza dough and then punch it by right click to make formed pizza dough, then you can shift right click to take it
