### ISSUE TITLE
Backware incompatible with Thermal Foundation's Iron Gear

### ISSUE THREAD

**Issue by MarkusBordihn** [Tiviacz1337/PizzaCraft#27]
I really like the mod, thanks for the good work, Unfortunately its overwrites the crafting recipe for "Iron Gear" in Thermal Foundation:
https://teamcofh.com/docs/1.12/thermal-foundation/iron-gear/

Would be nice to have an alternative crafting recipe like a stone or wodden block in the middle for the backware.

An additional block of iron is not recommend, because this conflicts with Rustic:
https://www.curseforge.com/minecraft/mc-mods/rustic

**Comment by Tiviacz1337** [comment]
Isn't it better to use mod that supports multiple recipes? Like NoMoreRecipeConflict
