### ISSUE TITLE
The pizza dough recipe has been removed from the game 

### ISSUE THREAD

**Issue by Titodelux** [Tiviacz1337/PizzaCraft#29]
It happens that I have not been able to start the mod properly since it is impossible for me to craft the pizza dough, it is probably due to an incompatibility with the vanilla pantry, which also includes its flour and its dough ...

**Comment by ElLiox** [comment]
Place the dough on any solid block, then right-click it repeatedly. Finally, you will get a round dough, right click it while holding shift to get it
