### ISSUE TITLE
[Enhancement] Multiple recipes at once in mortar and pestle block

### ISSUE THREAD

**Issue by Tiviacz1337** [Tiviacz1337/PizzaCraft#30]
As title says, I will to make it by myself sometime, but as for now, I have no clue how to start with it. Some help would be great :)

**Comment by gatoborrachon** [comment]
mmm, at least i think that this would have no sense, and if it is planned to add more Mortar recipes (and many of them use similar ingredients) this could become an issue. (in my irrelevant opinion)

**Comment by Tiviacz1337** [comment]
How it can be the issue? If coded right, it would make no problems

**Comment by gatoborrachon** [comment]
well, you are right, if you planify them perfectly there should not be any problems, (sorry)
