### ISSUE TITLE
Suggestion: Config Options, Crafttweaker Support

### ISSUE THREAD

**Issue by COLDW0LF** [Tiviacz1337/PizzaCraft#41]
Hi Tiviacz, just wanted to say; I adore the mod.
The visuals are perfect, and I love the immersion features. It's a very unique and detailed bit of work!
I thought I'd offer some suggestions, since I was working on a modpack and ran into a few ideas/problems.

1/
From what I could see in the configs, there's currently no way to disable specific seed types except Olives. 
This is somewhat of a problem if you're using other mods like Farmer's Delight or Some Assembly Required.
It's a huge shame, because the mods have such wonderful aesthetics and compliment each other perfectly!
If it's possible, I'd suggest adding a true/false toggle for each crop for maximum compatibility.

2/
Likewise, Crafttweaker support (or just documentation) for your mortar and pestle and basin would be amazing.
I'd gladly tweak all of the food recipes in my modpack just to work with your systems, they're superb! :)

**Comment by Spiderach** [comment]
any further info on this? being able to disable crops individually for modpack consistency would be greatly appreciated

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files/all?page=1&pageSize=20 added options to disable individual seeds
