### ISSUE TITLE
Fermenting cheese drops a glass bottle

### ISSUE THREAD

**Issue by COLDW0LF** [Tiviacz1337/PizzaCraft#42]
Hi,

Not sure if this is because I'm playing with Farmer's Delight or not (that adds the same behaviour to the cooking pot), 
but adding a mushroom or spider eye to the basin immediately pops out an empty glass bottle!

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files/3348904

**Comment by COLDW0LF** [comment]
You're a hero! Thanks for all your hard work :)
