### ISSUE TITLE
Server crashes when launching

### ISSUE THREAD

**Issue by ghost** [Tiviacz1337/PizzaCraft#43]
(last version in 1.16.5)
I am currently trying to make a server and the mod makes it unable to launch.
However when trying on client everything seems to be fine.
Here is the error:
`java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/color/ItemColors for invalid dist DEDICATED_SERVER`

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files/3348904
