### ISSUE TITLE
bugged pizza slice graphics

### ISSUE THREAD

**Issue by 0DeltaWaves** [Tiviacz1337/PizzaCraft#46]
After cutting a pizza with the knife, the model of the pizza becomes bugged. The pizza slices also appear to have bugged textures.

**Comment by Tiviacz1337** [comment]
Could you give me list of ingredients used on pizza?

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files/3429298

**Comment by 0DeltaWaves** [comment]
Perfect! Thank you so much for the quick bug fixes and update!
