### ISSUE TITLE
contents of basin/items on chopping board don't update properly on LAN multiplayer

### ISSUE THREAD

**Issue by 0DeltaWaves** [Tiviacz1337/PizzaCraft#47]
when one player places milk/sauce in the basin, it isn't there on the other player's screen. when the first player removes the completed cheese/sauce, it then appears (still in the basin) for the second player. if the second player right clicks on the basin, the contents appear to be collected but no item will be produced.

similarly, when one player places an item on a cutting board and cuts it, the item still appears to be on the cutting board for the second player.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files/3429298
