### ISSUE TITLE
right clicking a cooked pizza on an oven breaks the pizza's model

### ISSUE THREAD

**Issue by 0DeltaWaves** [Tiviacz1337/PizzaCraft#49]
the pizza becomes inaccessible and must be removed by left clicking. you cannot pick it up even with the peel after it's bugged.

**Comment by Tiviacz1337** [comment]
I can't reproduce this issue, can you give me more precious steps how to reproduce?

**Comment by 0DeltaWaves** [comment]
Looks like in the latest mod update (1.16.5-3.0.6) I cannot reproduce it either, it functions as expected. Thank you!
