### ISSUE TITLE
Suggestion - Logos or images on pizza boxes

### ISSUE THREAD

**Issue by DWX12** [Tiviacz1337/PizzaCraft#5]
There are several pizzas at the moment, but no way to tell the pizzas apart when they are in boxes, not to mention that they look rather plain in just white boxes.

At the very least, they could be a different color for each different type; however, a small design, logo, or even an image of the main ingredient on top of the box would make it look much better than it currently is and add in that small amount of detail (a brown mushroom for the mushroom pizza, pineapple for the pineapple pizza, cheese for the cheese pizza, etc.)

It's a cool little mod and I hope that you will continue to develop it even further.

**Comment by Tiviacz1337** [comment]
Thanks for suggestion I'll try to create something for each box to look different, probably ingridient on top.

**Comment by Tiviacz1337** [comment]
Post your opinion here, new update just rolled out with custom tops

**Comment by DWX12** [comment]
Sorry, I'm more active on Discord than I should be on Github.

You did an awesome job with the logos and I voiced my opinions of them on Discord. Unless anyone has any other comments, I feel they're good.

**Comment by DWX12** [comment]
Any reason to keep this issue open as I feel it has been resolved.

**Comment by s4sutler100** [comment]
Any anchovies yet?

catching fish then  they act like toppings?
