### ISSUE TITLE
olive fruit leaf blocks never mature?

### ISSUE THREAD

**Issue by 0DeltaWaves** [Tiviacz1337/PizzaCraft#50]
not sure if they never do or if they take a very long time. i can see via JEI that there's a mature state for them that have whitish olives, but the fruit leaf blocks on the saplings i planted/see in game stay in their young green state for days.
also, not sure if it's intended that there is only one fruit leaf block per olive tree.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files/3429298
