### ISSUE TITLE
corn is not obtainable without cheats

### ISSUE THREAD

**Issue by 0DeltaWaves** [Tiviacz1337/PizzaCraft#52]
A bug I missed in the last round, apologies. Unless there is a different method of obtaining corn, no matter how many jungle leaves or grass I break, I do not get any corn drops. Every other crop works.
This leaves only commands or creative mode if you want corn.

**Comment by Endercake6080** [comment]
The modder could add all crops to the wandering trader trading pool

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files/3685097
