### ISSUE TITLE
Pizza slice goes all glitchy

### ISSUE THREAD

**Issue by Endercake6080** [Tiviacz1337/PizzaCraft#54]
(see file and you'll see what I mean.
![Screenshot 2021-10-19 172302](https://user-images.githubusercontent.com/87301586/137941736-fe7c88d5-f8b6-4bcc-ae7e-534dd2b81839.png)
)

**Comment by Tiviacz1337** [comment]
Give me the list of ingredients on the slice

**Comment by Tiviacz1337** [comment]
Also mod version please?

**Comment by Endercake6080** [comment]
Version: PizzaCraft-1.16.5-3.0.5.jar
And this was the case with every Ingredient Mix I put on the Pizza (It didn't happend while it was empty tho)
