### ISSUE TITLE
Slices not stacking correctly

### ISSUE THREAD

**Issue by micaCons** [Tiviacz1337/PizzaCraft#61]
Hi!
When I slice any pizza they don't stack correctly, if I make a simple pizza with cheese I have 6 slice plus 1 slice than I can not stack with the other 6.
And this happeds with every pizza

**Comment by Tiviacz1337** [comment]
It's not a bug, it means that food value that pizza gives is not dividable by 6, which means 1 slice needs to have other food values and therefore it does not stack with others.
