### ISSUE TITLE
Crashy-Cheese

### ISSUE THREAD

**Issue by ddk111** [Tiviacz1337/PizzaCraft#66]
When i try to put a fermenting item in the basin the game crashes

**Comment by Tiviacz1337** [comment]
Can you provide crash log?

**Comment by ddk111** [comment]
The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Cannot invoke "com.tiviacz.pizzacraft.blockentity.BasinContent.getContentType()" because "content" is null
Kod zakończenia: -1

**Comment by Tiviacz1337** [comment]
version? also post full crash log

**Comment by ddk111** [comment]
1.18.1

**Comment by BlackShadow77** [comment]
> version? also post full crash log

I found same problem in a 1.18.1 server, i also send the crash log. It cause only the client to crash if enter in the chunk after right clicking on basin with fermenting item/s, server still go with no problem.

[Crash-Report.txt](https://github.com/Tiviacz1337/PizzaCraft/files/8515341/Crash-Report.txt)

**Comment by JustPista** [comment]
I also have this exact problem, same version, here's the crash report: 
[crash-2022-06-02_15.04.01-client.txt](https://github.com/Tiviacz1337/PizzaCraft/files/8824037/crash-2022-06-02_15.04.01-client.txt) .
 I also cannot play the world now, because every time I log into it, it crashes again.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files/3822779
