### ISSUE TITLE
Fishy pizza

### ISSUE THREAD

**Issue by s4sutler100** [Tiviacz1337/PizzaCraft#69]
PLease I thought you said you would allow fish on pizza?  Anchovies  are a common topping item just not ordered  a lot.  
Please allow cod or salmon as a topping?

**Comment by s4sutler100** [comment]
Here fishy fishy!

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files/all?page=1&pageSize=20 added fish fillet
