### ISSUE TITLE
Olive trees drop leaf blocks - MC 1.18.2

### ISSUE THREAD

**Issue by DWX12** [Tiviacz1337/PizzaCraft#71]
Forge - 40.1.41
Minecraft - 1.18.2
Pizzacraft - 5.1.1

Issue -
Olive trees drop entire leaf blocks when leaves decay or when broken. Unless olive trees are in loot chests then they are impossible to obtain.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files
fixed in latest versions
