### ISSUE TITLE
Wrong placement of model

### ISSUE THREAD

**Issue by 1Lir0n** [Tiviacz1337/PizzaCraft#72]
The model of the hat is in the center of the body instead of being on top of the head as it should.
Also, not so relevant, but I think you should try to make the chef shirt a bit less chunky/wide if possible.
The Chef hat problem:
![2022-07-24_19 56 24](https://user-images.githubusercontent.com/108737785/180658138-ad806fcb-1f61-47b3-affc-fca67f7ea8c5.png)
.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files
fixed in latest versions
