### ISSUE TITLE
Custom Pizza

### ISSUE THREAD

**Issue by tkxyooj** [Tiviacz1337/PizzaCraft#75]
Currently the mod has set layers for the pizza. Is it possible to open up the ingredient list to allow more ingredients in each layer, whether through a config file or thru a datapack? This feature would be really nice to have and solves the problem of asking for specific types of pizza.

**Comment by Tiviacz1337** [comment]
Of course it's possible by adding items to special tags, each layer is linked to tag.

you can check them here: https://github.com/Tiviacz1337/PizzaCraft/tree/1.19.2/src/main/resources/data/pizzacraft/tags/items/ingredients
