### ISSUE TITLE
[Enhancement] Allow vanilla foods on pizza

### ISSUE THREAD

**Issue by DeadlyAccurate** [Tiviacz1337/PizzaCraft#76]
It would be quite useful to be able to add sliced chicken, beef, and the Minecraft veggies to pizzas. Even cooler would be adding any foods through a config or datapack from other mods (like chocolate from Create to make dessert pizza).

**Comment by s4sutler100** [comment]
Please allow fish on pizza

**Comment by Tiviacz1337** [comment]
It's possible to add items to toppings tags via datapacks. As for now adding custom toppings is not available.
