### ISSUE TITLE
Crashing Issue: Various PizzaCraft items cause players to crash on a server

### ISSUE THREAD

**Issue by kedamono** [Tiviacz1337/PizzaCraft#77]
I made the PizzaCraft oven and chef's clothing: hat, jacket, pants, and shoes, and when I put the jacket on, I was crashed out of the game on a multiplayer server. Logging back on would work until I tried to open my inventory, and then I crashed. If other people looked at my character, they would crash. It got to a point where the server crashed. A mod wiped my inventory and that seemed to solve the problem, until I broke the oven and I crashed again. Another wipe of my inventory and that resolved the problem.

Here is the crash log of this event: https://bytebin.lucko.me/gZYTl4CghU

**Comment by Tiviacz1337** [comment]
Can you show the crashlog again? This link does not work

**Comment by kedamono** [comment]
[crash-2022-10-14_12.27.46-client.txt](https://github.com/Tiviacz1337/PizzaCraft/files/9789543/crash-2022-10-14_12.27.46-client.txt)
Here's a new crash log. I repro'd it in single player mode.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files
Fixed
