### ISSUE TITLE
[1.18.2] [5.1.1] Unexpected cheese wheel behavior

### ISSUE THREAD

**Issue by 0DeltaWaves** [Tiviacz1337/PizzaCraft#79]
Breaking a full cheese wheel makes it drop as an item, while crouch-right clicking it does nothing.
Breaking a partial cheese wheel deletes it, and so does crouch-right clicking it. Edit: Just right-clicking with an empty hand deletes it as well.

I think there should either be items for partial cheese blocks, so they don't get deleted when you try to move them, or just disable crouch-right clicking for them. On the other hand, crouch-right clicking should probably be enabled for full cheese wheels.

**Comment by Tiviacz1337** [comment]
To get cheese you have to click with knife, then it drops cheese items. Any other click eats the cheese just like cake.

**Comment by 0DeltaWaves** [comment]
Right, but what I'm saying is that the whole thing just disappears completely, even on a full hunger bar. It doesn't reduce by one slice like eating a cake or pizza does.
Also, performing the same actions on a full cheese wheel vs a partial one has inconsistent results like explained above. If you can pick up a full cheese wheel by mining it and making it drop as an item, the player will likely expect the same to be possible with partial wheels. Instead, attempting to do so will just delete it.
