### ISSUE TITLE
Anchovies

### ISSUE THREAD

**Issue by s4sutler100** [Tiviacz1337/PizzaCraft#8]
Can you add anchovies?

**Comment by Tiviacz1337** [comment]
I don't think I will add them, but I can add pizza which will use normal fishes as anchovies

**Comment by s4sutler100** [comment]
ok seems fair

**Comment by s4sutler100** [comment]
And Anchovies yet?

**Comment by Tiviacz1337** [comment]
Not yet

**Comment by s4sutler100** [comment]
How about now?

**Comment by s4sutler100** [comment]
You did add Anchovies or caught fish  to the Mod?
