### ISSUE TITLE
[Suggestion] new type of pizza topping

### ISSUE THREAD

**Issue by CplHartmann** [Tiviacz1337/PizzaCraft#82]
can we please get anchovy or any other fish as a topping for the pizzas

**Comment by s4sutler100** [comment]
> can we please get anchovy or any other fish as a topping for the pizzas

YES THANK YOU

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files/all?page=1&pageSize=20 added fish fillets
