### ISSUE TITLE
Crash on server caused by this mod

### ISSUE THREAD

**Issue by zachsai** [Tiviacz1337/PizzaCraft#84]
Forge team said i should report to you this crash
![image](https://user-images.githubusercontent.com/63996164/209641450-d6998a43-9941-447c-88c8-624efada2189.png)
https://pastebin.com/w3TdsvAi

1.19.2 forge

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files fixed
