### ISSUE TITLE
1.16.5 missing pizza

### ISSUE THREAD

**Issue by Namtheepic** [Tiviacz1337/PizzaCraft#85]
when i install this mod its missing alot of pizza and when i check the data pack i see this
![image](https://user-images.githubusercontent.com/121530069/209749072-0d1a2671-f052-487e-9763-c24dbf83f9e7.png)
its say that made for older version of minecraft
im using this version of this mod 

[PizzaCraft-1.16.5-3.0.9.jar](https://www.curseforge.com/minecraft/mc-mods/pizzacraft/files/4165034)
anyone help?

**Comment by Tiviacz1337** [comment]
What do you mean by missing pizza?
