### ISSUE TITLE
1.19.2 6.2.2 PizzaCraft | Toppings Vanish 

### ISSUE THREAD

**Issue by yorkmouse** [Tiviacz1337/PizzaCraft#90]
After cutting the pizza the topping vanish completely and the rest of the pizza looks like the empty variant.
Also does the 1.19.3 version have any other differences to the 6.2.2 version for 1.19.2? As the changelog only stated that it was updated to 1.19.3. 
Otherwise the oven doesn't need fuel. On the site it said that you need to fuel it and you can open the GUI with a shift click. That's currently not possible in 1.19.2 version. 
What is the use of olive oil? 
As a suggestion it would be nice if you added Champignons (as a new crop and topping)
Really a wonderful mod, keep it up!

**Comment by Tiviacz1337** [comment]
issue fixed in latest update https://legacy.curseforge.com/minecraft/mc-mods/pizzacraft/files
