### ISSUE TITLE
Crash when accidentally picking up rolled dough with Carry on

### ISSUE THREAD

**Issue by Darkmega18** [Tiviacz1337/PizzaCraft#91]
I got a crash for you. with pizzacraft version: 1.19.2-6.2.2 _(latest currently as far as curseforge update checking is concerned)_

[crash-2023-04-25_18.51.54-client.txt](https://github.com/Tiviacz1337/PizzaCraft/files/11320643/crash-2023-04-25_18.51.54-client.txt)

As for other mods, there are plenty, if you take a look in the log.

**Comment by Tiviacz1337** [comment]
fixed
