### ISSUE TITLE
MC1.16.5 & Forge 36.2.39 Version Check Error. Bug

### ISSUE THREAD

**Issue by Khan8615** [Tiviacz1337/PizzaCraft#96]
![image](https://github.com/Tiviacz1337/PizzaCraft/assets/14542835/fd633432-554f-4cee-b883-36f57080e5ee)

Fails to check versions properly.

MC 1.16.5
Forge 36.2.39
PizzaCraft-1.16.5-3.0.9.jar

Example of working version checker.
![image](https://github.com/Tiviacz1337/PizzaCraft/assets/14542835/2de43771-020d-4c98-9af0-2b232fa1df1a)

**Comment by Tiviacz1337** [comment]
version checker works, it shows null because you are already using the latest version possible
