### ISSUE TITLE
Olive trees spawning on top of other trees

### ISSUE THREAD

**Issue by Pendrag00n** [Tiviacz1337/PizzaCraft#97]
I'm pretty sure olive trees shouldn't be spawning on top of other trees...
![2023-08-06_09 44 38](https://github.com/Tiviacz1337/PizzaCraft/assets/88731722/8fec34f8-42d2-4904-af3b-073d24e8451f)

**Comment by Pendrag00n** [comment]
Like what is this fr 😭😭
![2023-08-06_09 50 25](https://github.com/Tiviacz1337/PizzaCraft/assets/88731722/d39a64ed-3715-4306-9b6b-bbdedbc34874)

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/pizzacraft/files/4685716 fixed

**Comment by Pendrag00n** [comment]
Thanks but could you push the fix into 1.19.3?

**Comment by Tiviacz1337** [comment]
1.19.3 is not supported

**Comment by Tiviacz1337** [comment]
I've pushed fix to 1.19.4 though
