### ISSUE TITLE
Raw pizza can be duplicated in the pizza station

### ISSUE THREAD

**Issue by Sukvii** [Tiviacz1337/PizzaCraft#98]
Just try to make multiple pizzas quickly with shift left click,and the materials are not consumed

**Comment by Sukvii** [comment]
Game version is 1.20.1,pizzacraft version is 7.0.6

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/pizzacraft/files
https://modrinth.com/mod/pizzacraft
Fixed
